
version: '3'
services:
  
  federated-client-0106fa6a-06d7-4991-a254-93d4ee1464a3:
    container_name: federated-client-0106fa6a-06d7-4991-a254-93d4ee1464a3
    build:
      context: app
      dockerfile: docker/client/Dockerfile
    environment:
      - SITE_ID=0106fa6a-06d7-4991-a254-93d4ee1464a3
      - SERVER_ADDRESS=federated-server
      - SERVER_PORT=5555
      - TEST_DATA_PATH=/test_data
      - SHARED_DATA_PATH=/shared_data
      - DATA_PATH=/data
      - VALUE_KEY=POWER_PRODUCTION
      - RUN_TRAINING=False
      - RUN_PREDICTION=True
    volumes:
      - client-0106fa6a-06d7-4991-a254-93d4ee1464a3-data:/data
      - /tmp/test_data/0106fa6a-06d7-4991-a254-93d4ee1464a3:/test_data:ro
      - /tmp/shared_data:/shared_data
    networks:
      - federated-network
  
  federated-client-1df9e630-c947-4b9a-89e2-c77b643506c5:
    container_name: federated-client-1df9e630-c947-4b9a-89e2-c77b643506c5
    build:
      context: app
      dockerfile: docker/client/Dockerfile
    environment:
      - SITE_ID=1df9e630-c947-4b9a-89e2-c77b643506c5
      - SERVER_ADDRESS=federated-server
      - SERVER_PORT=5555
      - TEST_DATA_PATH=/test_data
      - SHARED_DATA_PATH=/shared_data
      - DATA_PATH=/data
      - VALUE_KEY=POWER_PRODUCTION
      - RUN_TRAINING=False
      - RUN_PREDICTION=True
    volumes:
      - client-1df9e630-c947-4b9a-89e2-c77b643506c5-data:/data
      - /tmp/test_data/1df9e630-c947-4b9a-89e2-c77b643506c5:/test_data:ro
      - /tmp/shared_data:/shared_data
    networks:
      - federated-network
  
  federated-client-88ff6cd9-f81f-42e5-ad6c-b0ce7fc217bb:
    container_name: federated-client-88ff6cd9-f81f-42e5-ad6c-b0ce7fc217bb
    build:
      context: app
      dockerfile: docker/client/Dockerfile
    environment:
      - SITE_ID=88ff6cd9-f81f-42e5-ad6c-b0ce7fc217bb
      - SERVER_ADDRESS=federated-server
      - SERVER_PORT=5555
      - TEST_DATA_PATH=/test_data
      - SHARED_DATA_PATH=/shared_data
      - DATA_PATH=/data
      - VALUE_KEY=POWER_PRODUCTION
      - RUN_TRAINING=False
      - RUN_PREDICTION=True
    volumes:
      - client-88ff6cd9-f81f-42e5-ad6c-b0ce7fc217bb-data:/data
      - /tmp/test_data/88ff6cd9-f81f-42e5-ad6c-b0ce7fc217bb:/test_data:ro
      - /tmp/shared_data:/shared_data
    networks:
      - federated-network
  
  federated-client-ef5b7b47-37d4-4011-8b9f-fffd3020b0d9:
    container_name: federated-client-ef5b7b47-37d4-4011-8b9f-fffd3020b0d9
    build:
      context: app
      dockerfile: docker/client/Dockerfile
    environment:
      - SITE_ID=ef5b7b47-37d4-4011-8b9f-fffd3020b0d9
      - SERVER_ADDRESS=federated-server
      - SERVER_PORT=5555
      - TEST_DATA_PATH=/test_data
      - SHARED_DATA_PATH=/shared_data
      - DATA_PATH=/data
      - VALUE_KEY=POWER_PRODUCTION
      - RUN_TRAINING=False
      - RUN_PREDICTION=True
    volumes:
      - client-ef5b7b47-37d4-4011-8b9f-fffd3020b0d9-data:/data
      - /tmp/test_data/ef5b7b47-37d4-4011-8b9f-fffd3020b0d9:/test_data:ro
      - /tmp/shared_data:/shared_data
    networks:
      - federated-network
  

volumes:
  client-0106fa6a-06d7-4991-a254-93d4ee1464a3-data:
    external: false
  client-1df9e630-c947-4b9a-89e2-c77b643506c5-data:
    external: false
  client-88ff6cd9-f81f-42e5-ad6c-b0ce7fc217bb-data:
    external: false
  client-ef5b7b47-37d4-4011-8b9f-fffd3020b0d9-data:
    external: false
  

networks:
  federated-network:
    driver: bridge
    external: false
